### ISSUE TITLE
SSH keys permission error

### ISSUE THREAD

**Issue by raoulbhatia** [cisco-sso/kdk#12]
SSH keys are currently generated as root giving a permission denied on `./kdk ssh`.

```
ssh kdk@localhost -A -p 2022 -i ~/.kdk/ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
Warning: Permanently added '[localhost]:2022' (ECDSA) to the list of known hosts.
Load key "/home/kdk/.kdk/ssh/id_rsa": Permission denied
kdk@localhost's password:
```
_(I've executed the commands as user `kdk` with `uid 1002`.  `uid 1000` is a different user on the same system.)_
```
kdk@rb:~$ ls -aln ./.kdk/ssh/
total 16
drwxr-xr-x 2 1002 1002 4096 Jun 29 12:12 .
drwxr-xr-x 3 1002 1002 4096 Jun 29 12:12 ..
-rw------- 1    0    0 3247 Jun 29 12:12 id_rsa
-rw------- 1 1000 1000  743 Jun 29 12:12 id_rsa.pub
```

**Comment by dcwangmit01** [comment]
I'm unsure this is a bug. If the ssh keys are generated by one user, they won't be able to be read by another user.

**Comment by raoulbhatia** [comment]
Yes, I agree.  However, the script spins up a docker container to generate the SSH keys with root privileges.  Unless you use your computer as root I wouldn't see how this could work.
