### ISSUE TITLE
KDK contianer is not starting after upgrade to 1.8

### ISSUE THREAD

**Issue by soubhagyadiku** [cisco-sso/kdk#127]
Hi Team,

I upgraded the KDK from 1.6.1 to 1.8.0 yesterday. Now the KDK container is not getting started. Getting the below error.

---------
$ kdk ssh -d
time="2019-03-19T09:30:49+05:30" level=warning msg="Upgrade Available\n***************************************\nSome KDK components are out of date.\n  Latest Version:                      1.9.0\n  Binary Version:                      1.8.0\n  Image Tag:                           1.8.0\n  Container Present at Config Version: false\n\nPlease upgrade the KDK with the commands:\n  kdk update\n  kdk destroy\n  kdk ssh\n***************************************"
time="2019-03-19T09:30:49+05:30" level=info msg="Connecting to KDK container"
time="2019-03-19T09:30:49+05:30" level=info msg="KDK is not currently running.  Starting..."
time="2019-03-19T09:30:49+05:30" level=debug msg="Not pulling already present KDK Image" tag=1.8.0
time="2019-03-19T09:30:49+05:30" level=info msg="Keybase mirror already started"
time="2019-03-19T09:30:50+05:30" level=fatal msg="Failed to create KDK container" error="Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /host_mnt/c/Users/soupradh/.kdk/ssh/id_rsa.pub"

-----
Not sure where it is taking the /host_mnt/.

I have updated to 1.9.0, but also getting the same error.

Thanks,
Soubhayga

**Comment by dcwangmit01** [comment]
When the docker container runs, it is configured to mount locations on your host filesystem.  It appears those locations no longer exist.  Just re-init the configuration with `kdk init`, and try again.

**Comment by soubhagyadiku** [comment]
Hi David,

I tried kdk init multiple times, but it didn't work. So i reinstall docker and kubernetes and now it's working.

So closing the issue.

Thanks,
Soubhagya
