### ISSUE TITLE
Windows Keybase Anyconnect VPN: Not able to access mounted K: and C: drive while accessing KDK behind VPN

### ISSUE THREAD

**Issue by HussainGithub** [cisco-sso/kdk#128]
I am facing the below issue with KDK while accessing behind VPN
Not able to access mounted K: and C: drive and getting the error="A firewall is blocking file sharing between windows and containers"
Error response from daemon: "Drive sharing seems blocked by a firewall"

However everything is working as expected while using Cisco network

**Comment by dcwangmit01** [comment]
Would you mind googling around and trying to solve the problem, and posting a solution?

This seems highly relevant:
https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

We are unable to test this for you.   We only have macs outside of the firewall.

**Comment by dcwangmit01** [comment]
I bet your anyconnect VPN client is messing with your windows firewall rules.

**Comment by dcwangmit01** [comment]
You can try install keybase inside of the KDK.  We didn't add it in there because it would increase the docker image size by 400+MB.

https://keybase.io/docs/the_app/install_linux

**Comment by HussainGithub** [comment]
I have tried installing Keybase inside KDK and I am getting the same issue as - https://github.com/keybase/client/issues/16182

As suggested in the mentioned issue I would like to give a try by using `--privileged`, can you please let me know how to set `--privileged` flag while starting KDK?

One a side note, yes I have checked with IT and it seems that the port is blocked in AnyConnect as AnyConnect does not allow split tunneling when VPN'd.

**Comment by dcwangmit01** [comment]
@HussainGithub Thanks for doing the research.  I don't think there's a way around AnyConnect taking over your machine.  You may be able to use a different VPN client such as OpenConnect.

There's a way to configure the docker container directly.

When you executed `kdk init`, it created a configuration file in `~/.kdk/kdk/config.yaml`.  From there, you can edit both the HostConfig and the ContainerConfig sections, which enumerate all of the settings.

There is `HostConfig.Privileged = true`.  I think true is the default.

**Comment by HussainGithub** [comment]
@dcwangmit01 Hi David, as per company policy we are not allowed to use any other VPN client apart from CiscoAnyConnect. 

As per your latest comment I verified that `HostConfig.Privileged = true` in `~/.kdk/kdk/config.yaml`

**Comment by dcwangmit01** [comment]
@HussainGithub  Get yourself a Cisco CVO.

This is not a KDK issue.  It's a docker for windows issue.  ALL Docker mounts fail on Windows when connected to the Cisco VPN

https://github.com/docker/for-win/issues/360
