### ISSUE TITLE
Upgrade Executor to work around Python 3.7 incompatibility

### ISSUE THREAD

**Issue by raoulbhatia** [cisco-sso/kdk#16]
KDK doesn't work when using Python 3.7 i.e. via MacOS Homebew and Executor 20.0 due to `async`being a reserved keyword in Python 3.7 [1].

```python
Traceback (most recent call last):
  File "./kdk", line 12, in <module>
    from executor import execute
  File "/Users/raobhati/Dev/kdk/.venv/lib/python3.7/site-packages/executor/__init__.py", line 199
    if command.async:
                   ^
SyntaxError: invalid syntax
```

See [Python 3.7 reserved word: async #9](https://github.com/xolox/python-executor/issues/9)

[1] https://docs.python.org/3.7/reference/lexical_analysis.html?highlight=reserved%20word#keywords

**Comment by dcwangmit01** [comment]
@raoulbhatia Let's not invest in the python wrapper script.  It'll be replaced by the golang version shortly.

**Comment by raoulbhatia** [comment]
Looking forward to it.  However, I am not able to simply use `kdk` right now due to this bug.

**Comment by raoulbhatia** [comment]
https://github.com/xolox/python-executor/pull/11 fixes this issue.

**Comment by raoulbhatia** [comment]
```
cd ~Dev/kdk
source .venv/bin/activate
cd ./.venv/lib/python3.7/site-packages/executor
curl https://patch-diff.githubusercontent.com/raw/xolox/python-executor/pull/11.patch | patch -p2
```

You will need to skip over the patch for `CHANGELOG.rst`

**Comment by dcwangmit01** [comment]
Python KDK has now been deleted and replaced with golang one:

https://github.com/cisco-sso/kdk/pull/44
