### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by rtluckie** [cisco-sso/kdk#161]
We need to get fully automated CI sorted out.  The manual pushing of the docker containers is a serious PITA.

I would advocate moving from travis to circleci.

**Comment by dcwangmit01** [comment]
Sounds great.  Go for it.

**Comment by dcwangmit01** [comment]
BTW, I think the docker container builds in time in Travis right now.  It may not be broken.  It could depend on time of day network i/o.

**Comment by dcwangmit01** [comment]
I don't think Travis is broken.  Worked fine with 1.14.2 release:
https://travis-ci.org/cisco-sso/kdk?utm_medium=notification

**Comment by dcwangmit01** [comment]
@rtluckie  Please close if you agree

**Comment by dcwangmit01** [comment]
No response.  Closing.  Hasn't been a prlblem
