### ISSUE TITLE
KDK host-mount filesystem slowness on Mac

### ISSUE THREAD

**Issue by hangxie** [cisco-sso/kdk#177]
We need to bring docker lib to newer version to support cached, ref: https://docs.docker.com/docker-for-mac/osxfs-caching/

Performance test was done with kubernetes repo under golang docker container and `go list`

```
for D in $(seq 1 5); do cd /perftest/ && time go list ./... > /dev/null; done 2>&1 | grep real | tail -3
```

Comparision:
1. linux does not have much difference:
  * docker run -it --rm -v \`pwd\`/kubernetes:/perftest golang
> real	0m4.099s
> real	0m4.101s
> real	0m3.981s
  * docker run -it --rm -v \`pwd\`/kubernetes:/perftest:cached golang
> real	0m3.807s
> real	0m3.843s
> real	0m4.031s
2. mac: w/ cached is about 3 times faster than w/o cached
  * docker run -it --rm -v \`pwd\`/kubernetes:/perftest golang
> real	2m8.093s
> real	2m12.504s
> real	2m34.471s
  * docker run -it --rm -v \`pwd\`/kubernetes:/perftest:cached golang
> real	0m40.561s
> real	0m41.422s
> real	0m41.870s
```

**Comment by dcwangmit01** [comment]
@hangxie  Thanks for debugging this.  Should be an easy fix.

**Comment by hangxie** [comment]
Fix by https://github.com/cisco-sso/kdk/pull/178
