### ISSUE TITLE
Docker Hub images still tagged as debian-9.4

### ISSUE THREAD

**Issue by raoulbhatia** [cisco-sso/kdk#27]
https://hub.docker.com/r/ciscosso/kdk/builds/bfeml4dy4tmcbacjv79jslu/ shows that the Docker container was build `FROM debian:9.5` (see 9777ff46997cd62c8f0da051062ee4c37881f58b).

Once we add a new tag, we should also follow this change in https://github.com/cisco-sso/kdk/blob/6af44f630166b6bad2765c387bdb2ad0cedfa3b3/kdk#L94

**Comment by dcwangmit01** [comment]
Fixed.

https://hub.docker.com/r/ciscosso/kdk/tags/
