### ISSUE TITLE
Dockerfile for running awake based chart update

### ISSUE THREAD

**Issue by prabdeb** [cisco-sso/kdk#43]
Is it a good idea to have a Dockerfile that can help to update chart repo (cisco-sso/charts)?

Mainly the Dockerfile will have `awake`, `helm`, `kubectl`, `ansible` installed.

Current KDK Dockerfile might be little big for that!

I have tried to build it, size is coming close to 300MB.

**Comment by dcwangmit01** [comment]
Closing.  I think this project serves a different purpose.
